apiVersion: v1
kind: Pod
metadata:
  name: quadra-demo
spec:
  restartPolicy: Never
  nodeSelector:
    netint-type: "quadra"
  containers:
    - name: quadra-test
      image: busybox:1.35
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
          netint.ca/Quadra: 1
        limits:
          cpu: "200m"
          memory: "256Mi"
          netint.ca/Quadra: 1